pipeline{
    agent none
    stages{
        stage('build'){
            agent{
             node{
              label 'master'
              }
             }
            /*options{
                skipDefaultCheckout()
            }*/
            steps{
                echo "hello world"
            }
        }
    }
}
