pipeline{
    agent none
    stages{
        stage('build'){
            agent any
            /*options{
                skipDefaultCheckout()
            }*/
            steps{
                echo "hello world"
            }
        }
    }
}
