pipeline {
    agent none
    stages {
        stage('Checkout') {
            agent any
            steps {
                
                checkout([$class: 'GitSCM', 
				branches: [[name: "origin/master"]], 
				userRemoteConfigs: [[
                url: 'https://github.com/pipelineascodecourse/pipeline-agent-dockerfile-filename.git']]
				])
            }
        }
        stage('dockerfile'){            
            agent { 
                dockerfile {
					filename 'myCustomNameDockerfile'
                } 
            }            
            steps{
                sh 'cat /etc/lsb-release'			
            }
        }
    }
}

